accounts/urls.py
from django.urls import path
from .views import UserSignupView, UserSignInView, UserLogoutView, UserProfileView, change_password
from django.contrib.auth.views import LogoutView
urlpatterns = [
    path("signup/", UserSignupView.as_view(), name="signup"),
    path("signin/", UserSignInView.as_view(), name="signin"),
    path("profile/", UserProfileView.as_view(), name="profile"),

    path("change-password/", change_password, name="change_pass"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
]

bank_management/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import HomePageView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomePageView.as_view(), name="home"),
    path("accounts/", include("accounts.urls")),
    path("transactions/", include("transactions.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from .constants import ACCOUNT_TYPES, GENDER_TYPES
# Create your models here.


class UserBankAccountModel(models.Model):
    account = models.OneToOneField(
        User, related_name="account", on_delete=models.CASCADE)
    account_type = models.CharField(choices=ACCOUNT_TYPES, max_length=10)
    account_no = models.IntegerField(unique=True)
    birth_date = models.DateField(null=True, blank=True)
    gender = models.CharField(choices=GENDER_TYPES, max_length=10)
    balance = models.DecimalField(max_digits=12, default=0, decimal_places=2)
    isBankrupt = models.BooleanField(default=False)
    avatar = models.ImageField(
        upload_to="avatars/", default="avatars/default.png", blank=True, null=True)

    def __str__(self) -> str:
        return str(self.account_no)


class UserAddressModel(models.Model):
    user = models.OneToOneField(
        User, related_name="address", on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    postal_code = models.IntegerField()
    country = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.user.email

accounts/forms.py

from .models import UserBankAccountModel, UserAddressModel
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .constants import ACCOUNT_TYPES, GENDER_TYPES
from django.contrib.auth.models import User


class UserSignupForm(UserCreationForm):
    account_type = forms.ChoiceField(choices=ACCOUNT_TYPES)
    birth_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    gender = forms.ChoiceField(choices=GENDER_TYPES)
    street_address = forms.CharField(max_length=100)
    city = forms.CharField(max_length=100)
    postal_code = forms.IntegerField()
    country = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "account_type",
                  "birth_date", "gender", "street_address", "city", "postal_code", "country"]

    def save(self, commit=True):
        user = super().save(commit=False)

        if commit:
            user.save()
            account_type = self.cleaned_data.get("account_type")
            birth_date = self.cleaned_data.get("birth_date")
            gender = self.cleaned_data.get("gender")
            street_address = self.cleaned_data.get("street_address")
            postal_code = self.cleaned_data.get("postal_code")
            country = self.cleaned_data.get("country")
            city = self.cleaned_data.get("city")

            UserBankAccountModel.objects.create(
                account_type=account_type,
                birth_date=birth_date,
                gender=gender,
                account=user,
                account_no=1000000 + user.id
            )

            UserAddressModel.objects.create(
                street_address=street_address,
                user=user,
                postal_code=postal_code,
                city=city,
                country=country
            )
        return user

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({

                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 rounded '
                    'py-3 px-4 leading-tight focus:outline-none '
                    'focus:bg-white focus:border-gray-500'
                )
            })


class UserUpdateForm(forms.ModelForm):
    account_type = forms.ChoiceField(choices=ACCOUNT_TYPES)
    birth_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}))
    gender = forms.ChoiceField(choices=GENDER_TYPES)
    street_address = forms.CharField(max_length=100)
    city = forms.CharField(max_length=100)
    postal_code = forms.IntegerField()
    country = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 rounded '
                    'py-3 px-4 leading-tight focus:outline-none '
                    'focus:bg-white focus:border-gray-500'
                )
            })

        if self.instance:
            try:
                user_account = self.instance.account
                user_address = self.instance.address
            except UserBankAccountModel.DoesNotExist:
                user_account = None
                user_address = None

            if user_account:
                self.fields['account_type'].initial = user_account.account_type
                self.fields['gender'].initial = user_account.gender
                self.fields['birth_date'].initial = user_account.birth_date
                self.fields['street_address'].initial = user_address.street_address
                self.fields['city'].initial = user_address.city
                self.fields['postal_code'].initial = user_address.postal_code
                self.fields['country'].initial = user_address.country

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()

            user_account, created = UserBankAccountModel.objects.get_or_create(
                account=user)
            user_address, created = UserAddressModel.objects.get_or_create(
                user=user)

            user_account.account_type = self.cleaned_data['account_type']
            user_account.gender = self.cleaned_data['gender']
            user_account.birth_date = self.cleaned_data['birth_date']
            user_account.save()

            user_address.street_address = self.cleaned_data['street_address']
            user_address.city = self.cleaned_data['city']
            user_address.postal_code = self.cleaned_data['postal_code']
            user_address.country = self.cleaned_data['country']
            user_address.save()

        return user
    


accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserSignupForm, UserUpdateForm
from django.views.generic import FormView, View
from django.urls import reverse_lazy
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from transactions.utils.sendEmail import send_transaction_emails
from .models import UserBankAccountModel
# Create your views here.


class UserSignupView(FormView):
    template_name = 'accounts/signup.html'
    form_class = UserSignupForm
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        messages.success(self.request, "Signed up successfully")
        return super().form_valid(form)


class UserSignInView(LoginView):
    template_name = "accounts/signin.html"

    def get_success_url(self):
        messages.success(self.request, "Signed in successfully")
        return reverse_lazy("home")


class UserLogoutView(LogoutView):

    # def get_success_url(self):
    #     messages.info(self.request, "Logged out successfully")
    #     return reverse_lazy("home")
    
    # def get(self, request, *args, **kwargs):
    #     logout(request)
    #     messages.info(request, "Logged out successfully")
    #     print("User logged out")
    #     return redirect(reverse_lazy("home"))
  
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        """Allow logout via GET by calling post()"""
        return self.post(request, *args, **kwargs)
    def post(self, request, *args, **kwargs):
        self.next_page = reverse_lazy('home')
        logout(request)
        # Optional: Add a success message after logout
        messages.success(request, "You have been successfully logged out.")
        return super().post(request, *args, **kwargs)


class UserProfileView(View):
    template_name = "accounts/profile.html"

    def get(self, request):
        form = UserUpdateForm(instance=request.user)
        bank_account = UserBankAccountModel.objects.get(account=request.user)
        print(bank_account.avatar)
        return render(request, self.template_name, {"form": form, "avatar": bank_account.avatar})

    def post(self, request):
        form = UserUpdateForm(request.POST, instance=request.user)
        avatar = request.FILES.get("avatar")
        print(avatar)
        if form.is_valid():
            form.save()
            if avatar:
                # request.user.avatar = avatar
                # request.user.save()
                bank_account = UserBankAccountModel.objects.get(account=request.user)
                bank_account.avatar = avatar
                bank_account.save()
                
                print("Avatar updated successfully")
                print(bank_account.avatar)
            messages.success(self.request, "Profile updated Successfully")
            return redirect("profile")
        return render(request, self.template_name, {"form": form})


def change_password(request):
    if (request.method == "POST"):
        form = SetPasswordForm(request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            send_transaction_emails(
                request.user,
                request.user.email,
                f"Password A/C {request.user.account.account_no}",
                f"""Your password has been changed""")
            messages.success(request, "Password changed successfully")
            return redirect("profile")

    else:
        form = SetPasswordForm(user=request.user)

    return render(request, "accounts/change_password.html", {"form": form, "type": "Change Password"})

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block body %}
<section class="min-h-screen bg-cover bg-center bg-no-repeat bg-[url('/static/background/background.jpg')] py-1 px-1">

  <div class="w-full max-w-md bg-white rounded-2xl shadow-xl p-10 sm:p-12 relative z-10">
    
    <h2 class="text-4xl font-extrabold text-center text-indigo-900 mb-10 tracking-wide drop-shadow-md">
      Reset Password
    </h2>

    {% if form.non_field_errors %}
      <div class="mb-8 p-4 bg-red-50 border border-red-400 text-red-700 rounded-lg flex items-center space-x-3" role="alert" aria-live="assertive">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <ul class="list-disc list-inside text-sm font-medium">
          {% for error in form.non_field_errors %}
          <li>{{ error }}</li>
          {% endfor %}
        </ul>
      </div>
    {% endif %}

    <form method="post" class="space-y-6" novalidate>
      {% csrf_token %}
      
      {% for hidden_field in form.hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field }}
      {% endfor %}

      {% for field in form.visible_fields %}
        <div>
          <label for="{{ field.id_for_label }}" class="block mb-2 text-sm font-semibold text-gray-700">
            {{ field.label }}
          </label>
          <div class="relative">
            <input
              name="{{ field.name }}"
              id="{{ field.id_for_label }}"
              type="{{ field.widget_type }}"
              placeholder="{{ field.label }}"
              required
              aria-describedby="{{ field.id_for_label }}-error"
              class="w-full rounded-lg border border-gray-300 bg-gray-50 px-4 py-3 text-gray-900 placeholder-gray-400 shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-400 focus:outline-none transition"
            />
            {% if field.name == 'new_password' or field.name == 'confirm_password' %}
              <button
                type="button"
                aria-label="Toggle password visibility"
                class="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-indigo-600 focus:outline-none"
                onclick="togglePasswordVisibility('{{ field.id_for_label }}', this)"
                tabindex="-1"
              >
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" id="{{ field.id_for_label }}-eye-icon">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.477 0 8.268 2.943 9.542 7-1.274 4.057-5.065 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                </svg>
              </button>
            {% endif %}
          </div>
          {% if field.name == 'new_password' %}
            <div class="mt-2">
              <div class="w-full h-2 bg-gray-300 rounded-full overflow-hidden">
                <div id="password-strength-bar" class="h-2 bg-red-500 transition-all duration-300" style="width: 0%"></div>
              </div>
              <p id="password-strength-text" class="mt-1 text-xs font-semibold text-gray-600">Password Strength: <span class="font-bold">Too Weak</span></p>
            </div>
          {% endif %}
          {% if field.errors %}
            <p id="{{ field.id_for_label }}-error" class="mt-1 text-xs text-red-600" role="alert">
              {% for error in field.errors %}
                {{ error }}
              {% endfor %}
            </p>
          {% endif %}
        </div>
      {% endfor %}

      <button
        type="submit"
        class="w-full bg-indigo-600 hover:bg-indigo-700 focus:bg-indigo-700 text-white font-semibold py-3 rounded-lg shadow-lg transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-1"
      >
        Save
      </button>
    </form>
  </div>

  <script>
    function togglePasswordVisibility(inputId, btn) {
      const input = document.getElementById(inputId);
      const icon = document.getElementById(inputId + '-eye-icon');
      if (input.type === 'password') {
        input.type = 'text';
        icon.innerHTML = '<path stroke-linecap="round" stroke-linejoin="round" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.477 0-8.268-2.943-9.542-7a9.974 9.974 0 012.363-3.506m1.147-1.147A9.966 9.966 0 0112 5c4.477 0 8.268 2.943 9.542 7-0.42 1.344-1.155 2.58-2.163 3.59m-2.242 2.242L3 3" />';
      } else {
        input.type = 'password';
        icon.innerHTML = `
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.477 0 8.268 2.943 9.542 7-1.274 4.057-5.065 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
        `;
      }
    }

    const passwordInput = document.querySelector('input[name="new_password"]');
    const strengthBar = document.getElementById('password-strength-bar');
    const strengthText = document.getElementById('password-strength-text');

    if (passwordInput) {
      passwordInput.addEventListener('input', () => {
        const val = passwordInput.value;
        let strength = 0;

        if (val.length >= 8) strength++;
        if (/[A-Z]/.test(val)) strength++;
        if (/[0-9]/.test(val)) strength++;
        if (/[^A-Za-z0-9]/.test(val)) strength++;

        const widths = ['0%', '25%', '50%', '75%', '100%'];
        const colors = ['bg-red-500', 'bg-yellow-400', 'bg-yellow-500', 'bg-green-400', 'bg-green-600'];
        const texts = ['Too Weak', 'Weak', 'Medium', 'Strong', 'Very Strong'];

        strengthBar.style.width = widths[strength];
        colors.forEach(c => strengthBar.classList.remove(c));
        strengthBar.classList.add(colors[strength]);
        strengthText.querySelector('span').textContent = texts[strength];
      });
    }
  </script>
</section>
{% endblock %}


accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block head_title %}
<title>Profile</title>
{% endblock head_title %}

{% block body %}
<div class="max-w-5xl mx-auto px-4 py-12">
  <div class="bg-white shadow-xl rounded-3xl p-6 sm:p-10 space-y-10">

    <!-- Success Message -->
    {% if messages %}
      {% for message in messages %}
        <div class="bg-green-100 border border-green-400 text-green-800 px-6 py-4 rounded-lg animate-fade-in shadow">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}

    <!-- Non-field Errors -->
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
        <div class="bg-red-100 border border-red-400 text-red-800 px-6 py-4 rounded-lg animate-fade-in shadow">
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}

    <!-- Header -->
    <div class="flex flex-col sm:flex-row justify-between items-center gap-4 border-b pb-4">
      <h2 class="text-xl font-semibold text-gray-800">Account No: <span class="text-green-600 font-mono">*********</span></h2>
      <a href="{% url 'change_pass' %}" class="text-green-600 hover:text-green-700 font-medium">Change Password</a>
    </div>

    <!-- Avatar Upload -->
    
    <!-- Page Title -->
    <h1 class="text-3xl sm:text-4xl font-bold text-center text-gray-900">Update Profile</h1>

    <!-- Profile Form -->
    <form method="post" enctype="multipart/form-data" class="space-y-8">
      {% csrf_token %}
      {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
      {% endfor %}
<div class="flex justify-center">
      <label for="id_avatar" class="relative group cursor-pointer">
        <img
          id="avatarPreview"
          src="/media/{{ avatar }}"
          alt="Profile Avatar"
          class="w-32 h-32 rounded-full object-cover border-4 border-green-500 shadow-lg transition group-hover:scale-105"
        />
        <input type="file" name="avatar" id="id_avatar" accept="image/*" class="hidden" onchange="previewAvatar(event)">
        <div class="absolute bottom-0 right-0 bg-green-600 p-2 rounded-full shadow text-white group-hover:bg-green-700 transition">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M15.232 5.232l3.536 3.536M16.5 3a2.121 2.121 0 113 3L7 18.5 3 19l.5-4L16.5 3z" />
          </svg>
        </div>
      </label>
    </div>

      <div class="grid grid-cols-1 sm:grid-cols-2 gap-8">
        {% for field in form.visible_fields %}

          <div>
            <label for="{{ field.id_for_label }}" class="block mb-2 text-sm font-semibold text-gray-700">
              {{ field.label }}
            </label>
            {{ field }}
            {% if field.help_text %}
              <p class="text-xs text-gray-500 mt-1">{{ field.help_text }}</p>
            {% endif %}
            {% if field.errors %}
              {% for error in field.errors %}
                <p class="text-xs text-red-600 mt-1">{{ error }}</p>
              {% endfor %}
            {% endif %}
          </div>
        {% endfor %}

      </div>

      <!-- Buttons -->
      <div class="flex justify-end gap-4 pt-4">
        <button type="reset"
          class="bg-gray-200 hover:bg-gray-300 text-gray-800 font-semibold py-2 px-6 rounded-lg shadow-sm transition">
          Reset
        </button>
        <button type="submit"
          class="bg-green-600 hover:bg-green-700 text-white font-semibold py-2 px-8 rounded-lg shadow-lg transition">
          Update
        </button>
      </div>
    </form>
  </div>
</div>

<!-- JS Preview -->
<script>
  function previewAvatar(event) {
    const input = event.target;
    if (input.files && input.files[0]) {
      const reader = new FileReader();
      reader.onload = function (e) {
        document.getElementById('avatarPreview').src = e.target.result;
      };
      reader.readAsDataURL(input.files[0]);
    }
  }
</script>

<!-- Animation -->
<style>
  @keyframes fadeIn {
    from {
      opacity: 0;
      transform: translateY(-5px);
    }

    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  .animate-fade-in {
    animation: fadeIn 0.4s ease forwards;
  }

  input[type="text"],
  input[type="email"],
  input[type="file"],
  input[type="password"],
  select,
  textarea {
    @apply w-full rounded-lg border border-gray-300 bg-gray-50 px-4 py-3 text-gray-900 shadow-sm focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 transition;
  }
</style>
{% endblock %}

accounts/templates/accounts/signin.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block head_title %}
<title>Login | {{ title }}</title>
{% endblock head_title %}

{% block body %}
<!-- Gradient background -->
<div class="min-h-screen bg-gradient-to-br from-indigo-100 via-purple-50 to-white flex items-center justify-center px-4 py-12 sm:px-6 lg:px-8 relative overflow-hidden">

  <!-- Decorative blurred blobs -->
  <div class="absolute -top-20 -left-40 w-96 h-96 bg-indigo-300 rounded-full opacity-20 blur-3xl z-0"></div>
  <div class="absolute -bottom-24 -right-32 w-96 h-96 bg-purple-300 rounded-full opacity-20 blur-3xl z-0"></div>

  <!-- Login Card -->
  <div class="max-w-md w-full bg-white z-10 p-8 rounded-2xl shadow-2xl border border-gray-100 space-y-6">
    
    <!-- Header -->
    <div class="text-center">
      <img src="https://www.svgrepo.com/show/426943/login-circle.svg" alt="Login Icon" class="mx-auto h-16 w-16">
      <h2 class="mt-4 text-2xl font-bold text-gray-800">Welcome Back 👋</h2>
      <p class="text-sm text-gray-500">Login to access your dashboard</p>
    </div>

    <!-- Errors -->
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
        <div class="bg-red-100 border border-red-300 text-red-700 px-4 py-2 rounded-md text-sm font-medium">
          ⚠️ {{ error }}
        </div>
      {% endfor %}
    {% endif %}

    <!-- Form -->
    <form method="post" class="space-y-5">
      {% csrf_token %}
      {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
      {% endfor %}

      <!-- Username Field -->
      <div>
        <label for="{{ form.username.id_for_label }}" class="block text-gray-800 font-medium mb-1">Username</label>
        {% render_field form.username class="border border-gray-300 rounded-md px-3 py-2 w-full focus:ring-2 focus:ring-indigo-500 focus:outline-none" %}
        {% for error in form.username.errors %}
          <p class="text-sm text-red-500 mt-1">{{ error }}</p>
        {% endfor %}
      </div>

      <!-- Password Field -->
      <div>
        <label for="{{ form.password.id_for_label }}" class="block text-gray-800 font-medium mb-1">Password</label>
        {% render_field form.password class="border border-gray-300 rounded-md px-3 py-2 w-full focus:ring-2 focus:ring-indigo-500 focus:outline-none" %}
        {% for error in form.password.errors %}
          <p class="text-sm text-red-500 mt-1">{{ error }}</p>
        {% endfor %}
      </div>

      <!-- Submit Button -->
      <button type="submit" class="w-full bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-4 rounded-lg text-sm font-semibold transition shadow-md">
        Log In
      </button>
    </form>

    <!-- Optional Footer -->
    <div class="text-center text-sm text-gray-500">
      <p>Don’t have an account?
        <a href="{% url 'signup' %}" class="text-indigo-600 hover:underline font-medium">Register</a>
      </p>
    </div>

  </div>
</div>
{% endblock %}